version: '3.1'

services:

  shippy-cli-consignment:
    build: ./consignment-cli
  
  shippy-service-consignment:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
#      DB_HOST: "mongodb://datastore:27017"
      DB_HOST: "mongodb://host.docker.internal:27017"

  shippy-service-vessel:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
#      DB_HOST: "mongodb://datastore:27017"
      DB_HOST: "mongodb://host.docker.internal:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50053
    environment:
      MICRO_ADDRESS: ":50051"

  user-cli:
    build: ./user-cli
  database:
    image: postgres
    ports:
      - 5432:5432
#  datastore:
#    image: mongo
#    volumes:
#      - 'E:/work/databases/mongo-db-store:/data/db'
#    ports:
#      - 27017:27017
